global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'vps-monitor'
    environment: 'production'

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 15s
    metrics_path: /metrics

  # Node exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    metrics_path: /metrics

  # Docker container metrics
  - job_name: 'docker'
    static_configs:
      - targets: ['docker:9323']
    scrape_interval: 30s
    metrics_path: /metrics

  # n8n metrics (if enabled)
  - job_name: 'n8n'
    static_configs:
      - targets: ['n8n:5678']
    scrape_interval: 30s
    metrics_path: /metrics
    scrape_timeout: 10s

  # PostgreSQL metrics (if postgres_exporter is added)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s
    metrics_path: /metrics

  # Redis metrics (if redis_exporter is added)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s
    metrics_path: /metrics

  # Nginx Proxy Manager metrics
  - job_name: 'nginx-proxy-manager'
    static_configs:
      - targets: ['npm:81']
    scrape_interval: 30s
    metrics_path: /api/metrics
    scrape_timeout: 10s

  # pgAdmin metrics
  - job_name: 'pgadmin'
    static_configs:
      - targets: ['pgadmin:80']
    scrape_interval: 30s
    metrics_path: /metrics

  # Node-RED metrics
  - job_name: 'node-red'
    static_configs:
      - targets: ['node-red:1880']
    scrape_interval: 30s
    metrics_path: /metrics

  # Grafana metrics
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    scrape_interval: 30s
    metrics_path: /metrics

  # System metrics (if node_exporter is running on host)
  - job_name: 'system'
    static_configs:
      - targets: ['host.docker.internal:9100']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 5s

# Storage configuration for high performance
storage:
  tsdb:
    retention.time: 30d
    retention.size: 10GB
    wal-compression: true
