tunnel: ${CLOUDFLARE_TUNNEL_NAME:-my-vps-tunnel}
credentials-file: /root/.cloudflared/${TUNNEL_ID}.json

# Ingress rules for routing traffic through internal Docker network
ingress:
  # Route all traffic to Nginx Proxy Manager (internal network)
  - hostname: "*"
    service: http://npm:81
  # Catch-all rule
  - service: http_status:404
