tunnel: ${CLOUDFLARE_TUNNEL_NAME:-my-vps-tunnel}
credentials-file: /root/.cloudflared/${TUNNEL_ID}.json

# No ingress rules defined here - will be managed via NPM
# The tunnel will connect to NPM on port 81

ingress:
  # Route all traffic to Nginx Proxy Manager
  - hostname: "*"
    service: http://npm:81
  # Catch-all rule
  - service: http_status:404
